services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    restart: on-failure
    env_file:
      - .env
    networks:
      inception:

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_vol:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      inception:
    # expose:
    #   - "9000"

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      inception:
    restart: on-failure
    volumes:
      - mariadb_vol:/var/lib/mysql

networks:
  inception:

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: "none"
      device: "$HOME/data/wordpress_vol"
      o: "bind"
  mariadb_vol:
    driver: local
    driver_opts:
      type: "none"
      device: "$HOME/data/mariadb_vol"
      o: "bind"
