services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./wordpress_vol:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    restart: on-failure
    env_file:
      - .env
    networks:
      inception:

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - ./wordpress_vol:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      inception:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      inception:
    restart: on-failure
    volumes:
      - mariadb_vol:/var/lib/mysql

networks:
  inception:

volumes:
  wordpress_vol:
  mariadb_vol:
